# Generated by Django 4.2.25 on 2025-10-27 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(default='United States', max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('popularity_score', models.FloatField(default=0)),
                ('search_hits', models.PositiveIntegerField(default=0)),
                ('bookings_30d', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'region', 'country')},
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='travel.location')),
            ],
        ),
    ]
